language: cpp

compiler:
  - gcc
  - clang

env:
  - AUTOTOOLS=yes
  - AUTOTOOLS=no

before_install:
  - git clone https://github.com/hcatlin/sass-spec.git
  - git clone https://github.com/jbussdieker/sassc.git

install:
  - autoreconf -i
  - ./configure --prefix=/usr
  - sudo make install
  - cd sassc
  - autoreconf -i
  - ./configure --prefix=/usr
  - sudo make install
  - cd ..

script:
  - cd sass-spec
  - ./sass-spec.rb -c sassc -s --ignore-todo

